import { Equipment, EquipmentStatus } from '@/types';

// Fixed dates to prevent hydration errors
const EQUIPMENT_DATES = [
  '2024-01-01T00:00:00.000Z',
  '2024-01-02T00:00:00.000Z',
  '2024-01-03T00:00:00.000Z',
  '2024-01-04T00:00:00.000Z',
  '2024-01-05T00:00:00.000Z',
  '2024-01-06T00:00:00.000Z',
];

export const mockEquipmentData: Equipment[] = [
  {
    id: 1,
    name: 'Sony Alpha A7 III',
    description: 'Máy ảnh mirrorless full-frame với cảm biến 24.2MP, quay video 4K và chống rung 5 trục in-body.',
    dailyRate: 1500000,
    availableQuantity: 5,
    category: 'Máy ảnh',
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop&q=80',
        alt: 'Sony Alpha A7 III',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop&q=80',
        alt: 'Sony Alpha A7 III - Side view',
      },
    ],
    specifications: {
      resolution: '24.2MP',
      videoQuality: '4K',
      batteryLife: '610 shots',
      weight: '650g',
      dimensions: '126.9 x 95.6 x 73.7mm',
    },
    status: EquipmentStatus.ACTIVE,
    brand: 'Sony',
    model: 'Alpha A7 III',
    isAvailable: true,
    rating: 4.8,
    reviewCount: 124,
    createdAt: EQUIPMENT_DATES[0],
    updatedAt: EQUIPMENT_DATES[0],
  },
  {
    id: 2,
    name: 'Canon EOS R5',
    description: 'Máy ảnh mirrorless cao cấp với cảm biến 45MP, quay video 8K RAW và hệ thống lấy nét Dual Pixel CMOS AF II.',
    dailyRate: 2200000,
    availableQuantity: 3,
    category: 'Máy ảnh',
    images: [
      {
        id: 3,
        url: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop&q=80',
        alt: 'Canon EOS R5',
      },
    ],
    specifications: {
      resolution: '45MP',
      videoQuality: '8K',
      batteryLife: '320 shots',
      weight: '738g',
      dimensions: '138.5 x 97.5 x 88mm',
    },
    status: EquipmentStatus.ACTIVE,
    brand: 'Canon',
    model: 'EOS R5',
    isAvailable: true,
    rating: 4.9,
    reviewCount: 89,
    createdAt: EQUIPMENT_DATES[1],
    updatedAt: EQUIPMENT_DATES[1],
  },
  {
    id: 3,
    name: 'Sony 24-70mm f/2.8 GM',
    description: 'Ống kính zoom tiêu chuẩn chuyên nghiệp với khẩu độ f/2.8 cố định, thuộc dòng G Master cao cấp.',
    dailyRate: 1180000,
    availableQuantity: 8,
    category: 'Ống kính',
    images: [
      {
        id: 4,
        url: 'https://images.unsplash.com/photo-1567450840746-5a6c3b49b7c2?w=800&h=600&fit=crop&q=80',
        alt: 'Sony 24-70mm f/2.8 GM',
      },
    ],
    specifications: {
      focalLength: '24-70mm',
      aperture: 'f/2.8',
      weight: '886g',
      filterSize: '82mm',
    },
    status: EquipmentStatus.ACTIVE,
    brand: 'Sony',
    model: '24-70mm f/2.8 GM',
    isAvailable: true,
    rating: 4.7,
    reviewCount: 156,
    createdAt: EQUIPMENT_DATES[2],
    updatedAt: EQUIPMENT_DATES[2],
  },
  {
    id: 4,
    name: 'Canon 85mm f/1.2L USM',
    description: 'Ống kính portrait chuyên nghiệp với khẩu độ f/1.2 siêu rộng, tạo hiệu ứng bokeh đẹp mắt.',
    dailyRate: 980000,
    availableQuantity: 4,
    category: 'Ống kính',
    images: [
      {
        id: 5,
        url: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop&q=80',
        alt: 'Canon 85mm f/1.2L USM',
      },
    ],
    specifications: {
      focalLength: '85mm',
      aperture: 'f/1.2',
      weight: '1025g',
      filterSize: '77mm',
    },
    status: EquipmentStatus.ACTIVE,
    brand: 'Canon',
    model: '85mm f/1.2L USM',
    isAvailable: true,
    rating: 4.6,
    reviewCount: 203,
    createdAt: EQUIPMENT_DATES[3],
    updatedAt: EQUIPMENT_DATES[3],
  },
  {
    id: 5,
    name: 'DJI Ronin-S Gimbal',
    description: 'Gimbal cầm tay 3 trục chuyên nghiệp cho máy ảnh DSLR và mirrorless, ổn định hình ảnh hoàn hảo.',
    dailyRate: 1750000,
    availableQuantity: 2,
    category: 'Phụ kiện',
    images: [
      {
        id: 6,
        url: 'https://images.unsplash.com/photo-1567450840746-5a6c3b49b7c2?w=800&h=600&fit=crop&q=80',
        alt: 'DJI Ronin-S Gimbal',
      },
    ],
    specifications: {
      maxPayload: '3.6kg',
      batteryLife: '12 hours',
      weight: '1.84kg',
      operatingTemperature: '-10°C to 45°C',
    },
    status: EquipmentStatus.ACTIVE,
    brand: 'DJI',
    model: 'Ronin-S',
    isAvailable: true,
    rating: 4.5,
    reviewCount: 78,
    createdAt: EQUIPMENT_DATES[4],
    updatedAt: EQUIPMENT_DATES[4],
  },
  {
    id: 6,
    name: 'Nikon D850',
    description: 'Máy ảnh DSLR full-frame 45.7MP với khả năng quay video 4K và hệ thống lấy nét 153 điểm.',
    dailyRate: 1650000,
    availableQuantity: 0, // Out of stock
    category: 'Máy ảnh',
    images: [
      {
        id: 7,
        url: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop&q=80',
        alt: 'Nikon D850',
      },
    ],
    specifications: {
      resolution: '45.7MP',
      videoQuality: '4K',
      batteryLife: '1840 shots',
      weight: '1005g',
    },
    status: EquipmentStatus.INACTIVE,
    brand: 'Nikon',
    model: 'D850',
    isAvailable: false,
    rating: 4.4,
    reviewCount: 95,
    createdAt: EQUIPMENT_DATES[5],
    updatedAt: EQUIPMENT_DATES[5],
  },
];

export const mockCategories = [
  { id: 'camera', name: 'Máy ảnh', equipmentCount: 25 },
  { id: 'lens', name: 'Ống kính', equipmentCount: 18 },
  { id: 'lighting', name: 'Đèn chiếu sáng', equipmentCount: 12 },
  { id: 'audio', name: 'Thiết bị âm thanh', equipmentCount: 8 },
  { id: 'video', name: 'Thiết bị quay phim', equipmentCount: 15 },
  { id: 'drone', name: 'Flycam/Drone', equipmentCount: 6 },
  { id: 'accessories', name: 'Phụ kiện', equipmentCount: 30 },
];

export const mockBrands = [
  { id: 'canon', name: 'Canon', equipmentCount: 15 },
  { id: 'sony', name: 'Sony', equipmentCount: 12 },
  { id: 'nikon', name: 'Nikon', equipmentCount: 10 },
  { id: 'panasonic', name: 'Panasonic', equipmentCount: 8 },
  { id: 'fujifilm', name: 'Fujifilm', equipmentCount: 6 },
  { id: 'olympus', name: 'Olympus', equipmentCount: 5 },
  { id: 'dji', name: 'DJI', equipmentCount: 4 },
];