import { Equipment, EquipmentStatus } from '@/types';

export const mockEquipmentData: Equipment[] = [
  {
    id: '1',
    name: 'Sony Alpha A7 III',
    description: 'Máy ảnh mirrorless full-frame với cảm biến 24.2MP, quay video 4K và chống rung 5 trục in-body.',
    price: 1500000,
    quantity: 5,
    categoryId: 'camera',
    category: {
      id: 'camera',
      name: 'Máy ảnh',
      description: 'Camera equipment',
      slug: 'camera',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    images: [
      {
        id: 'img1',
        url: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop&q=80',
        alt: 'Sony Alpha A7 III',
        isPrimary: true,
      },
      {
        id: 'img1-2',
        url: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop&q=80',
        alt: 'Sony Alpha A7 III - Side view',
        isPrimary: false,
      },
    ],
    specifications: {
      resolution: '24.2MP',
      videoQuality: '4K',
      batteryLife: '610 shots',
      weight: '650g',
      dimensions: '126.9 x 95.6 x 73.7mm',
    },
    status: EquipmentStatus.AVAILABLE,
    brand: 'Sony',
    model: 'Alpha A7 III',
    isAvailable: true,
    rating: 4.8,
    reviewsCount: 124,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: '2',
    name: 'Canon EOS R5',
    description: 'Máy ảnh mirrorless cao cấp với cảm biến 45MP, quay video 8K RAW và hệ thống lấy nét Dual Pixel CMOS AF II.',
    price: 2200000,
    quantity: 3,
    categoryId: 'camera',
    category: {
      id: 'camera',
      name: 'Máy ảnh',
      description: 'Camera equipment',
      slug: 'camera',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    images: [
      {
        id: 'img2',
        url: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop&q=80',
        alt: 'Canon EOS R5',
        isPrimary: true,
      },
    ],
    specifications: {
      resolution: '45MP',
      videoQuality: '8K',
      batteryLife: '320 shots',
      weight: '738g',
      dimensions: '138.5 x 97.5 x 88mm',
    },
    status: EquipmentStatus.AVAILABLE,
    brand: 'Canon',
    model: 'EOS R5',
    isAvailable: true,
    rating: 4.9,
    reviewsCount: 89,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Sony 24-70mm f/2.8 GM',
    description: 'Ống kính zoom tiêu chuẩn chuyên nghiệp với khẩu độ f/2.8 cố định, thuộc dòng G Master cao cấp.',
    price: 1180000,
    quantity: 8,
    categoryId: 'lens',
    category: {
      id: 'lens',
      name: 'Ống kính',
      description: 'Camera lens',
      slug: 'lens',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    images: [
      {
        id: 'img3',
        url: 'https://images.unsplash.com/photo-1567450840746-5a6c3b49b7c2?w=800&h=600&fit=crop&q=80',
        alt: 'Sony 24-70mm f/2.8 GM',
        isPrimary: true,
      },
    ],
    specifications: {
      focalLength: '24-70mm',
      aperture: 'f/2.8',
      weight: '886g',
      filterSize: '82mm',
    },
    status: EquipmentStatus.AVAILABLE,
    brand: 'Sony',
    model: '24-70mm f/2.8 GM',
    isAvailable: true,
    rating: 4.7,
    reviewsCount: 156,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Canon 85mm f/1.2L USM',
    description: 'Ống kính portrait chuyên nghiệp với khẩu độ f/1.2 siêu rộng, tạo hiệu ứng bokeh đẹp mắt.',
    price: 980000,
    quantity: 4,
    categoryId: 'lens',
    category: {
      id: 'lens',
      name: 'Ống kính',
      description: 'Camera lens',
      slug: 'lens',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    images: [
      {
        id: 'img4',
        url: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=800&h=600&fit=crop&q=80',
        alt: 'Canon 85mm f/1.2L USM',
        isPrimary: true,
      },
    ],
    specifications: {
      focalLength: '85mm',
      aperture: 'f/1.2',
      weight: '1025g',
      filterSize: '77mm',
    },
    status: EquipmentStatus.AVAILABLE,
    brand: 'Canon',
    model: '85mm f/1.2L USM',
    isAvailable: true,
    rating: 4.6,
    reviewsCount: 203,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'DJI Ronin-S Gimbal',
    description: 'Gimbal cầm tay 3 trục chuyên nghiệp cho máy ảnh DSLR và mirrorless, ổn định hình ảnh hoàn hảo.',
    price: 1750000,
    quantity: 2,
    categoryId: 'accessories',
    category: {
      id: 'accessories',
      name: 'Phụ kiện',
      description: 'Camera accessories',
      slug: 'accessories',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    images: [
      {
        id: 'img5',
        url: 'https://images.unsplash.com/photo-1567450840746-5a6c3b49b7c2?w=800&h=600&fit=crop&q=80',
        alt: 'DJI Ronin-S Gimbal',
        isPrimary: true,
      },
    ],
    specifications: {
      maxPayload: '3.6kg',
      batteryLife: '12 hours',
      weight: '1.84kg',
      operatingTemperature: '-10°C to 45°C',
    },
    status: EquipmentStatus.AVAILABLE,
    brand: 'DJI',
    model: 'Ronin-S',
    isAvailable: true,
    rating: 4.5,
    reviewsCount: 78,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Nikon D850',
    description: 'Máy ảnh DSLR full-frame 45.7MP với khả năng quay video 4K và hệ thống lấy nét 153 điểm.',
    price: 1650000,
    quantity: 0, // Out of stock
    categoryId: 'camera',
    category: {
      id: 'camera',
      name: 'Máy ảnh',
      description: 'Camera equipment',
      slug: 'camera',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    images: [
      {
        id: 'img6',
        url: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=600&fit=crop&q=80',
        alt: 'Nikon D850',
        isPrimary: true,
      },
    ],
    specifications: {
      resolution: '45.7MP',
      videoQuality: '4K',
      batteryLife: '1840 shots',
      weight: '1005g',
    },
    status: EquipmentStatus.OUT_OF_STOCK,
    brand: 'Nikon',
    model: 'D850',
    isAvailable: false,
    rating: 4.4,
    reviewsCount: 95,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockCategories = [
  { id: 'camera', name: 'Máy ảnh', equipmentCount: 25 },
  { id: 'lens', name: 'Ống kính', equipmentCount: 18 },
  { id: 'lighting', name: 'Đèn chiếu sáng', equipmentCount: 12 },
  { id: 'audio', name: 'Thiết bị âm thanh', equipmentCount: 8 },
  { id: 'video', name: 'Thiết bị quay phim', equipmentCount: 15 },
  { id: 'drone', name: 'Flycam/Drone', equipmentCount: 6 },
  { id: 'accessories', name: 'Phụ kiện', equipmentCount: 30 },
];

export const mockBrands = [
  { id: 'canon', name: 'Canon', equipmentCount: 15 },
  { id: 'sony', name: 'Sony', equipmentCount: 12 },
  { id: 'nikon', name: 'Nikon', equipmentCount: 10 },
  { id: 'panasonic', name: 'Panasonic', equipmentCount: 8 },
  { id: 'fujifilm', name: 'Fujifilm', equipmentCount: 6 },
  { id: 'olympus', name: 'Olympus', equipmentCount: 5 },
  { id: 'dji', name: 'DJI', equipmentCount: 4 },
];